name: linting
on:
  pull_request:
    branches:
      - "main"
jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Linting on Code Base
        uses: github/super-linter/slim@v4.9.4
        env:
          DEFAULT_BRANCH: main
          DEFAULT_WORKSPACE: .
          VALIDATE_TYPESCRIPT_ES: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_MARKDOWN: true
          VALIDATE_JSON: true
          VALIDATE_CPP: true
          VALIDATE_CLANG_FORMAT: true
          GITHUB_TOKEN: InvalidToken
